insert into medicine (id, name, indications, contraindications, adverse_reactions, precautions, codebar, active_ingredients, ms_record, generic) values (1, 'Dorflex', 'Dorflex é Indicado para dores de cabeça e para dor musculares, que resultam de processos traumáticos ou inflamatórios, sendo constituído por dipirona sódica, ocitrato de orfenadrina e cafeína.', 'Dorflex está contraindicado para mulheres grávidas ou que estão amamentando, crianças com menos de 12 anos de idade.', 'Quando a dose diária é aumentada, podem ocorrer efeitos adversos como: redução ou aumento do ritmo cardíaco, arritmias cardíacas, palpitações, sede, diminuição da sudorese, dilatação da pupila, fraqueza, náusea, vômitos, dor de cabeça', 'Em tratamentos prolongados, seu médico deve controlar o perfil das características do sangue, com hemogramas frequentes, e também a função do fígado e rins.', 7891058002916, 'Cada comprimido contém 300 mg de dipirona monoidratada, 35 mg de citrato de orfenadrina (equivalente a 20,4 mg de orfenadrina base) e 50 mg de cafeína anidra', 123, 0);
insert into medicine (id, name, indications, contraindications, adverse_reactions, precautions, codebar, active_ingredients, ms_record, generic) values (2, 'Amoxicilina', 'Amoxicilina 500 mg é indicado para o tratamento de infecções causadas por bactérias sensíveis à Amoxicilina, como infecções urinárias, de ouvido ou respiratórias, amigdalite, sinusite ou vaginite.', 'Este medicamento não pode ser administrado nem ingerido por pessoas alérgicas à amoxicilina, a outros antibióticos penicilínicos ou antibióticos similares, chamados cefalosporinas.', 'Reações alérgicas graves (como ocorre com outros antibióticos), candidíase mucocutânea, hipercinesia, vertigem e convulsões.', 'Antes de iniciar o tratamento com amoxicilina tri-hidratada, informe seu médico se você já apresentou reação alérgica a algum antibiótico.', 1122334455667, 'benzoato de sódio, citrato de sódio di- hidratado, dióxido de silício, goma xantana, celulose microcristalina e carmelose sódica, sacarose, silicona, corante vermelho ponceau 4R, aroma de morango', 234, 1);
insert into medicine (id, name, indications, contraindications, adverse_reactions, precautions, codebar, active_ingredients, ms_record, generic) values (3, 'Minoxidil', 'É indicado pelo profissional especializado para o tratamento da alopecia androgenética, nome científico da calvície hereditária.', 'É contra-indicado em pacientes com hipersensibilidade ao minoxidil ou outros componentes da fórmula.', 'Crescimento indesejados de cabelos em outras partes do corpo, coceira e couro cabeludo descamando', 'Deve-se verificar se o couro cabeludo apresenta-se saudável e normal antes de usar o Minoxidil 5% (substância ativa).', 1234567891012, 'Ingrediente ativo - Minoxidil 5%, outros ingredientes.', 456, 0);
insert into medicine (id, name, indications, contraindications, adverse_reactions, precautions, codebar, active_ingredients, ms_record, generic) values (4, 'Dipirona', 'A dipirona é um medicamento analgésico, antipirético e espasmolítico, muito utilizado no tratamento de dores e febre, normalmente provocadas por gripes e resfriados.', 'A Dipirona está contra-indicada em pacientes com intolerância conhecida aos derivados pirazolônicos (antipirina, aminopirina e dipirona) ou pacientes com discrasias sangüíneas1. É contra-indicado no primeiro trimestre da gestação.', 'A dipirona pode causar choque ana filático, reações anafiláticas/anafilactoides, reações de hipersensibilidade, com manifestações cutâneas do tipo alérgicas', 'Nos três primeiros meses e nas últimas seis semanas da gestação (deve ser evitado), em pacientes com asma e infecções respiratórias crônicas.', 3344556677889, 'fosfato de sódio monobásico, fosfato de sódio dibásico, sacarina sódica e água purificada.', 567, 0);
insert into medicine (id, name, indications, contraindications, adverse_reactions, precautions, codebar, active_ingredients, ms_record, generic) values (5, 'Bromoprida', 'A Bromoprida é um remédio indicado para facilitar a digestão, aliviar náuseas ou vômitos e evitar crises de refluxo gástrico.', 'Não se deve usar em grávidas ou durante amamentação e em caso de alergia a qualquer componente da fórmula.', 'Os efeitos colaterais mais comuns incluem inquietação, sonolência, cansaço, insônia, dor de cabeça, tontura, náusea, vermelhidão e coceira na pele, diarreia ou prisão de ventre.', 'Nos doentes diabéticos, o uso deste remédio pode levar a necessidade de ajuste da dose de insulina.', 3322110987654, 'sacarina sódica, propilenoglicol, metilparabeno, essência Tuti-frutti, corante amarelo tartrazina 5, ácido cítrico, álcool etílico, água purificada', 024, 0);
insert into medicine (id, name, indications, contraindications, adverse_reactions, precautions, codebar, active_ingredients, ms_record, generic) values (6, 'Carvedilol', 'carvedilol é indicado para tratamento de hipertensão arterial, isoladamente ou em associação a outros agentes anti-hipertensivos, especialmente diuréticos tiazídicos.', ' Não usar este medicamento se possuir insuficiência cardíaca descompensada/instável necessitando medicamento intravenoso para aumentar a força do coração.', ' Tonturas, alterações visuais e bradicardia. Tontura, síncope, cefaleia e astenia são, normalmente, leves e ocorrem, geralmente, no início do tratamento.', 'Sua capacidade para dirigir veículo ou operar máquinas pode estar comprometida devido a tonturas e cansaço.',  1234098765454, 'lactose monoidratada, celulose microcristalina, povidona, croscarmelose sódica, laurilsulfato de sódio, dióxido de silício, talco, estearato de magnésio', 987, 0);
insert into medicine (id, name, indications, contraindications, adverse_reactions, precautions, codebar, active_ingredients, ms_record, generic) values (7, 'Rivotril', 'Está indicado isoladamente ou como adjuvante no tratamento das crises epilépticas mioclônicas, acinéticas, ausências típicas (petit mal), ausências atípicas (síndrome de Lennox-Gastaut).', 'Não deve ser usado por pacientes com história de sensibilidade aos benzodiazepínicos ou a qualquer dos componentes da fórmula, por pacientes com insuficiência respiratória grave ou com insuficiência hepática grave.', 'Os efeitos colaterais que ocorreram com maior freqüência com Rivotril® são referentes à depressão do SNC.', 'Não tome Rivotril com álcool e/ou depressores do sistema nervoso central', 9977804567234, 'clonazepam...0,5 mg, lactose, amido de milho, amido pré-gelatinizado, óxido de ferro amarelo, óxido férrico, talco, estearato de magnésio.', 098, 0);


insert into user (id, name, username, password, cpf, email, identity, birth_date, phone, cell_phone) values (5000,'Paulo Henrique', 'paulo','admin','00000000000','paulo@med4you.com', 11554887, '25/10/1993', '32654758', '34999999999');
insert into user (id, name, username, password, cpf, email, identity, birth_date, phone, cell_phone) values (5001,'Eduardo', 'eduardo','admin','11951504666','eduardo@hotmail.com', '14886995', '18/04/1994', '32616877', '34996626481');
insert into user (id, name, username, password, cpf, email, responsable_user_id, firebase_token, identity, birth_date, phone, cell_phone) values (5002,'Filipe', 'filipe','admin','22222222222','filipe@med4you.com', 5001,'d9MV6594FXQ%3AAPA91bFhcVhEblFhIPOf2wAZpkvWvFKU0-GwHrZNCT3iDHWyKw3hqujejDwwdQ1_wXxQQHQb-CwQJ7hvSe9BMPo9Kw-JawqWjQbfGvPWbyOicOG0rhdr1BS8E4ISeM0rQPgKaSusJZ2o', '33446776', '04/01/1989', '34369874', '34996638789');
insert into user (id, name, username, password, cpf, email, responsable_user_id) values (5003,'Administrador', 'admin','admin','33333333333','admin@med4you.com', 5000);


Insert into doctor (id, name, phone, crm) values (1, 'Pedro Antônio', '34987678765', '23342231');
Insert into doctor (id, name, phone, crm) values (2, 'José Augusto', '34998872351', '59823447');
Insert into doctor (id, name, phone, crm) values (3, 'Joao da Silva', '34999736895', '29512334');

insert into medical_prescription (id, doctor_id, cid, medical_prescription_text, user_id) values (1, 1, '123', 'Dramin 100mg - tomar 01 comp', 5000);
insert into medical_prescription (id, doctor_id, cid, medical_prescription_text, user_id) values (2, 3, '156', 'Buscopam composto gotas - tomar 35 gotas de 8/8 hrs', 5002);
insert into medical_prescription (id, doctor_id, cid, medical_prescription_text, user_id) values (3, 2, '323', 'Amoxicilina 875mg - tomar 1 comprimido de 8/8 hrs', 5001);